import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { PrismaClient, Prisma } from '@prisma/client';

export interface SeedFood {
  externalId: string;
  name: string;
  brand?: string | null;
  barcode?: string | null;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  servingName?: string;
  isGramBased?: boolean;
  source: 'GENERIC' | 'OPEN_FOOD_FACTS';
}

function toRow(f: SeedFood): Prisma.FoodItemUncheckedCreateInput {
  return {
    externalId: f.externalId,
    name: f.name,
    brand: f.brand ?? null,
    barcode: f.barcode ?? null,
    caloriesPer100g: f.caloriesPer100g,
    proteinPer100g: f.proteinPer100g,
    carbsPer100g: f.carbsPer100g,
    fatPer100g: f.fatPer100g,
    servingName: f.servingName ?? '100g',
    isGramBased: f.isGramBased ?? true,
    source: f.source,
  };
}

export async function upsertFoods(prisma: PrismaClient, foods: SeedFood[]): Promise<number> {
  for (const f of foods) {
    const row = toRow(f);
    await prisma.foodItem.upsert({
      where: { externalId: f.externalId },
      update: row,
      create: row,
    });
  }
  return foods.length;
}

export function loadFoodSeedData(): SeedFood[] {
  const dir = join(process.cwd(), 'prisma', 'data');
  const core = JSON.parse(readFileSync(join(dir, 'foods.core.json'), 'utf-8')) as SeedFood[];
  let off: SeedFood[] = [];
  try {
    off = JSON.parse(readFileSync(join(dir, 'foods.off.json'), 'utf-8')) as SeedFood[];
  } catch {
    // foods.off.json is generated by scripts/import-off-foods.ts; empty/absent is fine.
  }
  return [...core, ...off];
}
